version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all-github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    assignees:
      - "JulianVIE"

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm-patch:
        update-types:
          - "patch"
      npm-minor:
        update-types:
          - "minor"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 7
    labels:
      - "dependencies"
      - "npm"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    assignees:
      - "JulianVIE"
