/**
 * All fiat (and commodity) currencies whose rates are fetched from the
 * Coinbase /v2/exchange-rates?currency=BTC endpoint (see src/hooks/useRates.ts).
 *
 * The list was sourced from the Coinbase /v2/currencies endpoint, which
 * returns the set of fiat currencies for which Coinbase publishes rates.
 * If Coinbase adds or removes currencies, both this file and ui-i18n.ts
 * (the translation keys) should be updated together.
 *
 * Codes are lowercase to match the internal convention used throughout the app.
 */

/** Americas */
const AMERICAS = [
  "ars",
  "arsmep",
  "awg",
  "bbd",
  "bmd",
  "bob",
  "brl",
  "bsd",
  "bzd",
  "cad",
  "clp",
  "clf",
  "cop",
  "crc",
  "cuc",
  "cup",
  "dop",
  "gtq",
  "gyd",
  "hnl",
  "htg",
  "jmd",
  "kyd",
  "mxn",
  "nio",
  "pab",
  "pen",
  "pyg",
  "srd",
  "svc",
  "ttd",
  "usd",
  "uyu",
  "vef",
  "ves",
  "xcd",
] as const;

/** Europe */
const EUROPE = [
  "all",
  "azn",
  "bam",
  "bgn",
  "byn",
  "byr",
  "chf",
  "czk",
  "dkk",
  "eur",
  "gbp",
  "gel",
  "ggp",
  "hrk",
  "huf",
  "isk",
  "imp",
  "jep",
  "ltl",
  "lvl",
  "mdl",
  "mkd",
  "nok",
  "pln",
  "ron",
  "rsd",
  "rub",
  "sek",
  "shp",
  "skk",
  "try",
  "uah",
] as const;

/** Middle East & North Africa */
const MENA = [
  "aed",
  "bhd",
  "dzd",
  "egp",
  "iqd",
  "irr",
  "jod",
  "kwd",
  "lbp",
  "lyd",
  "mad",
  "omr",
  "qar",
  "sar",
  "sdg",
  "syp",
  "tnd",
  "yer",
] as const;

/** Africa */
const AFRICA = [
  "aoa",
  "bif",
  "bwp",
  "cdf",
  "cve",
  "djf",
  "etb",
  "ghs",
  "gmd",
  "gnf",
  "kes",
  "kmf",
  "lrd",
  "lsl",
  "mga",
  "mro",
  "mru",
  "mur",
  "mwk",
  "mzn",
  "nad",
  "ngn",
  "rwf",
  "sbd",
  "scr",
  "sll",
  "sos",
  "ssp",
  "std",
  "szl",
  "tzs",
  "ugx",
  "xaf",
  "xof",
  "zar",
  "zmk",
  "zmw",
  "zwd",
] as const;

/** Asia & Pacific */
const ASIA_PACIFIC = [
  "afn",
  "amd",
  "ang",
  "aud",
  "bdt",
  "bnd",
  "btn",
  "cnh",
  "cny",
  "fjd",
  "fkp",
  "hkd",
  "idr",
  "ils",
  "inr",
  "jpy",
  "kgs",
  "khr",
  "krw",
  "kzt",
  "lak",
  "lkr",
  "mmk",
  "mnt",
  "mop",
  "mvr",
  "myr",
  "npr",
  "nzd",
  "pgk",
  "php",
  "pkr",
  "sgd",
  "thb",
  "tjs",
  "tmm",
  "tmt",
  "twd",
  "uzs",
  "vnd",
  "vuv",
  "wst",
  "xpf",
] as const;

/** Commodities & Special Drawing Rights */
const COMMODITIES = ["xag", "xau", "xdr", "xpd", "xpt"] as const;

export const FIAT_CURRENCY_CODES = [
  ...AMERICAS,
  ...EUROPE,
  ...MENA,
  ...AFRICA,
  ...ASIA_PACIFIC,
  ...COMMODITIES
] as const;

export type FiatCurrencyCode = (typeof FIAT_CURRENCY_CODES)[number];

export const FIAT_CURRENCY_CODES_SET = new Set<FiatCurrencyCode>(FIAT_CURRENCY_CODES);

export const FIAT_CURRENCY_NAMES: Record<FiatCurrencyCode, string> = {
  // Americas
  ars: "Argentine Peso",
  arsmep: "Argentine Blue Dollar",
  awg: "Aruban Florin",
  bbd: "Barbadian Dollar",
  bmd: "Bermudian Dollar",
  bob: "Bolivian Boliviano",
  brl: "Real",
  bsd: "Bahamian Dollar",
  bzd: "Belize Dollar",
  cad: "Canadian Dollar",
  clp: "Chilean Peso",
  clf: "Unidad de Fomento",
  cop: "Colombian Peso",
  crc: "Costa Rican Colón",
  cuc: "Cuban Convertible Peso",
  cup: "Cuban Peso",
  dop: "Dominican Peso",
  gtq: "Guatemalan Quetzal",
  gyd: "Guyanese Dollar",
  hnl: "Honduran Lempira",
  htg: "Haitian Gourde",
  jmd: "Jamaican Dollar",
  kyd: "Cayman Islands Dollar",
  mxn: "Mexican Peso",
  nio: "Nicaraguan Córdoba",
  pab: "Panamanian Balboa",
  pen: "Peruvian Sol",
  pyg: "Paraguayan Guaraní",
  srd: "Surinamese Dollar",
  svc: "Salvadoran Colón",
  ttd: "Trinidad and Tobago Dollar",
  usd: "US Dollar",
  uyu: "Uruguayan Peso",
  vef: "Venezuelan Bolívar",
  ves: "Venezuelan Bolívar Soberano",
  xcd: "East Caribbean Dollar",
  // Europe
  all: "Albanian Lek",
  azn: "Azerbaijani Manat",
  bam: "Bosnia-Herzegovina Convertible Mark",
  bgn: "Bulgarian Lev",
  byn: "Belarusian Ruble",
  byr: "Belarusian Ruble (legacy)",
  chf: "Swiss Franc",
  czk: "Czech Koruna",
  dkk: "Danish Krone",
  eur: "Euro",
  gbp: "British Pound",
  gel: "Georgian Lari",
  ggp: "Guernsey Pound",
  hrk: "Croatian Kuna",
  huf: "Hungarian Forint",
  isk: "Icelandic Króna",
  imp: "Isle of Man Pound",
  jep: "Jersey Pound",
  ltl: "Lithuanian Litas (legacy)",
  lvl: "Latvian Lats (legacy)",
  mdl: "Moldovan Leu",
  mkd: "Macedonian Denar",
  nok: "Norwegian Krone",
  pln: "Polish Złoty",
  ron: "Romanian Leu",
  rsd: "Serbian Dinar",
  rub: "Russian Ruble",
  sek: "Swedish Krona",
  shp: "Saint Helenian Pound",
  skk: "Slovak Koruna (legacy)",
  try: "Turkish Lira",
  uah: "Ukrainian Hryvnia",
  // Middle East & North Africa
  aed: "UAE Dirham",
  bhd: "Bahraini Dinar",
  dzd: "Algerian Dinar",
  egp: "Egyptian Pound",
  iqd: "Iraqi Dinar",
  irr: "Iranian Rial",
  jod: "Jordanian Dinar",
  kwd: "Kuwaiti Dinar",
  lbp: "Lebanese Pound",
  lyd: "Libyan Dinar",
  mad: "Moroccan Dirham",
  omr: "Omani Rial",
  qar: "Qatari Riyal",
  sar: "Saudi Riyal",
  sdg: "Sudanese Pound",
  syp: "Syrian Pound",
  tnd: "Tunisian Dinar",
  yer: "Yemeni Rial",
  // Africa
  aoa: "Angolan Kwanza",
  bif: "Burundian Franc",
  bwp: "Botswana Pula",
  cdf: "Congolese Franc",
  cve: "Cape Verdean Escudo",
  djf: "Djiboutian Franc",
  etb: "Ethiopian Birr",
  ghs: "Ghanaian Cedi",
  gmd: "Gambian Dalasi",
  gnf: "Guinean Franc",
  kes: "Kenyan Shilling",
  kmf: "Comorian Franc",
  lrd: "Liberian Dollar",
  lsl: "Lesotho Loti",
  mga: "Malagasy Ariary",
  mro: "Mauritanian Ouguiya (legacy)",
  mru: "Mauritanian Ouguiya",
  mur: "Mauritian Rupee",
  mwk: "Malawian Kwacha",
  mzn: "Mozambican Metical",
  nad: "Namibian Dollar",
  ngn: "Nigerian Naira",
  rwf: "Rwandan Franc",
  sbd: "Solomon Islands Dollar",
  scr: "Seychellois Rupee",
  sll: "Sierra Leonean Leone",
  sos: "Somali Shilling",
  ssp: "South Sudanese Pound",
  std: "São Tomé & Príncipe Dobra",
  szl: "Swazi Lilangeni",
  tzs: "Tanzanian Shilling",
  ugx: "Ugandan Shilling",
  xaf: "Central African CFA Franc",
  xof: "West African CFA Franc",
  zar: "South African Rand",
  zmk: "Zambian Kwacha (legacy)",
  zmw: "Zambian Kwacha",
  zwd: "Zimbabwean Dollar",
  // Asia & Pacific
  afn: "Afghan Afghani",
  amd: "Armenian Dram",
  ang: "Netherlands Antillean Gulden",
  aud: "Australian Dollar",
  bdt: "Bangladeshi Taka",
  bnd: "Brunei Dollar",
  btn: "Bhutanese Ngultrum",
  cnh: "Chinese Yuan Offshore",
  cny: "Chinese Yuan",
  fjd: "Fijian Dollar",
  fkp: "Falkland Pound",
  hkd: "Hong Kong Dollar",
  idr: "Indonesian Rupiah",
  ils: "Israeli New Sheqel",
  inr: "Indian Rupee",
  jpy: "Japanese Yen",
  kgs: "Kyrgyzstani Som",
  khr: "Cambodian Riel",
  krw: "South Korean Won",
  kzt: "Kazakhstani Tenge",
  lak: "Lao Kip",
  lkr: "Sri Lankan Rupee",
  mmk: "Myanmar Kyat",
  mnt: "Mongolian Tögrög",
  mop: "Macanese Pataca",
  mvr: "Maldivian Rufiyaa",
  myr: "Malaysian Ringgit",
  npr: "Nepalese Rupee",
  nzd: "New Zealand Dollar",
  pgk: "Papua New Guinean Kina",
  php: "Philippine Peso",
  pkr: "Pakistani Rupee",
  sgd: "Singapore Dollar",
  thb: "Thai Baht",
  tjs: "Tajikistani Somoni",
  tmm: "Turkmenistani Manat (legacy)",
  tmt: "Turkmenistani Manat",
  twd: "New Taiwan Dollar",
  uzs: "Uzbekistan Som",
  vnd: "Vietnamese Đồng",
  vuv: "Vanuatu Vatu",
  wst: "Samoan Tala",
  xpf: "CFP Franc",
  // Commodities & Special Drawing Rights
  xag: "Silver (Troy Ounce)",
  xau: "Gold (Troy Ounce)",
  xdr: "Special Drawing Rights",
  xpd: "Palladium",
  xpt: "Platinum",
};

/**
 * Fiat currencies pinned to the top of the currency selector.
 * Order here is the display order.
 */
export const PINNED_FIAT_CURRENCY_CODES = ["usd", "eur", "gbp", "cny", "jpy"] as const satisfies FiatCurrencyCode[];
